// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMANpizza.Models;

namespace VMANpizza.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VMANpizza.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("VMANpizza.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PizzaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("QtyL")
                        .HasColumnType("float");

                    b.Property<double>("QtyM")
                        .HasColumnType("float");

                    b.Property<double>("QtyS")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("VMANpizza.Models.ViewModel.OrderPizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("QtyLbac")
                        .HasColumnType("float");

                    b.Property<double>("QtyLche")
                        .HasColumnType("float");

                    b.Property<double>("QtyLchk")
                        .HasColumnType("float");

                    b.Property<double>("QtyLmus")
                        .HasColumnType("float");

                    b.Property<double>("QtyLpep")
                        .HasColumnType("float");

                    b.Property<double>("QtyLsal")
                        .HasColumnType("float");

                    b.Property<double>("QtyMbac")
                        .HasColumnType("float");

                    b.Property<double>("QtyMche")
                        .HasColumnType("float");

                    b.Property<double>("QtyMchk")
                        .HasColumnType("float");

                    b.Property<double>("QtyMmus")
                        .HasColumnType("float");

                    b.Property<double>("QtyMpep")
                        .HasColumnType("float");

                    b.Property<double>("QtyMsal")
                        .HasColumnType("float");

                    b.Property<double>("QtySbac")
                        .HasColumnType("float");

                    b.Property<double>("QtySche")
                        .HasColumnType("float");

                    b.Property<double>("QtySchk")
                        .HasColumnType("float");

                    b.Property<double>("QtySmus")
                        .HasColumnType("float");

                    b.Property<double>("QtySpep")
                        .HasColumnType("float");

                    b.Property<double>("QtySsal")
                        .HasColumnType("float");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrderPizza");
                });
#pragma warning restore 612, 618
        }
    }
}
